### Get all blogs
GET http://localhost:3003/api/blogs


### Add new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Refactor toimii",
  "author": "Kirsikka",
  "url": "https://example.com",
  "likes": 3
}

### Add new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "kirsi",
  "name": "Kirsi Vister",
  "password": "salainen123"
}

### Get all users
GET http://localhost:3003/api/users